### ISSUE TITLE
Fill out sequencing list

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/xchain#3]
- [Sequencing section](https://github.com/0xFableOrg/xchain/blob/master/pages/sequencing-list.md)

**Comment by namn-grg** [comment]
Hey @norswap, for this, I have to focus on gathering all the projects and proposals right? and, overviewing them and coming up with some solution comes later in the next stage I assume?

**Comment by norswap** [comment]
@namn-grg Yes, though if you want to go ahead and write up a *short* summary (like a paragraph or two) on the projects, that's fine. Might be difficult to nuance when writing so short, but ideally might provide some saliant points of comparison across the projects. Might be best left for later, but up to you1

What's good if you're up for it is to start identifying features and trade-off points that we can use in analysis later.
